services:
  decideforme:
    build:
      target: prod
    ports:
      - 3000:3000
    restart: always
    networks:
      - app-network

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/config.conf
    networks:
      - app-network

networks:
  app-network: