services:
  decideforme:
    build:
      target: prod
    container_name: decideforme
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    networks:
      - app-network

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/config.conf
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    networks:
      - app-network
      - cert-network
    depends_on:
      - decideforme

  certbot:
    image: certbot/dns-route53
    container_name: certbot
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - certbot_conf:/etc/letsencrypt:rw
      - certbot_www:/var/www/certbot:rw
      - ./scripts/nginx-reload.sh:/etc/letsencrypt/renewal-hooks/post/nginx-reload.sh:ro
    networks:
      - cert-network
    command: certonly --dns-route53 -d ${APP_DOMAIN} -d ${APP_DOMAIN_WWW} -m ${CERT_MAIL} --agree-tos --force-renewal

volumes:
  certbot_conf:
  certbot_www:

networks:
  app-network:
  cert-network: