# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "feature/pwa" ]
  pull_request:
    branches: [ "feature/pwa" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule 
        # at https://nodejs.org/en/about/releases/
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3
    
    - name: Install & build  
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: deploy via web-deploy
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ vars.SERVER_HOSTNAME }}
        ssh-port: ${{ vars.SERVER_PORT }}
        remote-user: ${{ vars.SERVER_USER }}
        private-ssh-key: ${{ secrets.SERVER_SSH_PASS }}
        source-path: ./build/
        destination-path: ~/html/eoxpwa/
        rsync-options: --dry-run --verbose --human-readable --stats



    # - name: upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: eox
    #     path: ./build/


  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: eox
